Add debug for ethers lib to track Infura call
omgnetwork/optimism-v2 pull request #28
Opened 2021-10-06 18:45 UTC by trangtran-enya

2021-10-06 23:29 UTC, boyuan-chen requested changes

2021-10-06 23:29 UTC, cby3149 commented on packages/batch-submitter/src/exec/run-batch-submitter.ts
> +  const setEtherDebug = (configs: { provider: StaticJsonRpcProvider }) => {
It's not the correct place. It's in `src/exec/run-batch-submitter.ts`.

2021-10-06 23:29 UTC, cby3149 commented on packages/message-relayer/src/exec/withdraw.ts
> +const loggerOptions: LoggerOptions = {
This file isn't use in production.

2021-10-08 08:15 UTC, InoMurko commented
@trangtran-enya can we figure out, from the calls - who is making them?
so that we have separate dashboards for every service. this way we could figure out who's making the most requests, and than gradually figure out which rpc calls are most used by which service

2021-10-08 16:33 UTC, cby3149 commented on packages/batch-submitter/src/exec/run-batch-submitter.ts
> +  const setEtherDebug = (configs: { provider: StaticJsonRpcProvider }) => {
My fault. You are right.

2021-10-08 17:03 UTC, trangtran-enya commented
> The monitor also makes RPC calls to infura. The PR of adding the monitor service is on the way.

Okie, so I wait for those PRs and update afterward

2021-10-21 20:09 UTC, cby3149 approved these changes

2021-12-04 12:49 UTC, InoMurko commented
ping @trangtran-enya @cby3149

2022-02-23 20:03 UTC, CAPtheorem commented
stale pr - closing for now

2022-02-23 20:03 UTC, closed without merging