DTL and L2Geth fixes
omgnetwork/optimism-v2 pull request #383
Opened 2022-02-15 04:06 UTC by CAPtheorem

1. Clean up the init for Turing fields inside the DTL
2. Patch the print-ETH vulnerability (this was patched privately in the past; this is the public commit of the patch)

2022-02-15 04:08 UTC, Boyuan-Chen approved these changes

2022-02-15 06:02 UTC, InoMurko requested changes

2022-02-15 06:02 UTC, InoMurko commented on integration-tests/test/stress-tests.spec.ts
> +    it.only(
Only should be removed

2022-02-17 18:42 UTC, CAPtheorem commented on integration-tests/test/stress-tests.spec.ts
> +    it.only(
done!

2022-02-17 21:01 UTC, merged